
package com.example.consumingwebservice.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "productPort", targetNamespace = "http://www.example.com/demosoap/gen")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductPort {


    /**
     * 
     * @param getProductRequest
     * @return
     *     returns com.example.consumingwebservice.ws.GetProductResponse
     */
    @WebMethod
    @WebResult(name = "getProductResponse", targetNamespace = "http://www.example.com/demosoap/gen", partName = "getProductResponse")
    public GetProductResponse getProduct(
        @WebParam(name = "getProductRequest", targetNamespace = "http://www.example.com/demosoap/gen", partName = "getProductRequest")
        GetProductRequest getProductRequest);

    /**
     * 
     * @param getProductsRequest
     * @return
     *     returns com.example.consumingwebservice.ws.GetProductsResponse
     */
    @WebMethod
    @WebResult(name = "getProductsResponse", targetNamespace = "http://www.example.com/demosoap/gen", partName = "getProductsResponse")
    public GetProductsResponse getProducts(
        @WebParam(name = "getProductsRequest", targetNamespace = "http://www.example.com/demosoap/gen", partName = "getProductsRequest")
        GetProductsRequest getProductsRequest);

    /**
     * 
     * @param postProductRequest
     * @return
     *     returns com.example.consumingwebservice.ws.PostProductResponse
     */
    @WebMethod
    @WebResult(name = "postProductResponse", targetNamespace = "http://www.example.com/demosoap/gen", partName = "postProductResponse")
    public PostProductResponse postProduct(
        @WebParam(name = "postProductRequest", targetNamespace = "http://www.example.com/demosoap/gen", partName = "postProductRequest")
        PostProductRequest postProductRequest);

}
